### ISSUE TITLE
Typo in `src/pos/exit_util.ts`: "grater" should be "greater"

### ISSUE THREAD

**Issue by flanagansteve** [0xPolygon/wiki#108]
In [the error message](https://github.com/maticnetwork/matic.js/blob/481d51af6627bf6fa0ec505974c9d57a5ba2ad4c/src/pos/exit_util.ts#L300) for an out-of-range token index, the message says the index is "grater" than the number of tokens in this transaction, but it should be "greater"

I tried to open a PR for this, but got a 403 from https://github.com/maticnetwork/matic.js.git/ when trying to push to my feature branch.

**Comment by DannyS03** [comment]
Hi @flanagansteve, thanks for flagging this. This issue should be opened in https://github.com/maticnetwork/matic.js/. I am unable to transfer the issue because the "matic.js" repo is under the legacy "maticnetwork" GitHub org.

I'd suggest raising a PR directly on the repo.

**Comment by flanagansteve** [comment]
> Hi @flanagansteve, thanks for flagging this. This issue should be opened in https://github.com/maticnetwork/matic.js/. I am unable to transfer the issue because the "matic.js" repo is under the legacy "maticnetwork" GitHub org.
> 
> I'd suggest raising a PR directly on the repo.

Aha, don't know how the issue ended up here instead! Sorry about that @DannyS03
