### ISSUE TITLE
rootchain deploy - Wiki not updated.

### ISSUE THREAD

**Issue by devudilip** [0xPolygon/wiki#32]
I am following the wiki to create a supernet.
I have followed the Demo Geth Instance and running the below command throws an error. 

```
./polygon-edge rootchain deploy \
  --genesis ./genesis.json \
  --json-rpc http://127.0.0.1:8545 \
  --test
```

Edge is expecting the --stake-token and --stake-manager key, as I used --test I don't have these.

**Comment by DannyS03** [comment]
Was previously addressed. Please reopen if otherwise.
