### ISSUE TITLE
Migrate zkEVM documentation

### ISSUE THREAD

**Issue by DannyS03** [0xPolygon/wiki#45]
## Context

In the pursuit of creating a unified and authoritative source of information for Polygon, we are planning to migrate the zkEVM documentation back to the [Polygon Wiki](https://wiki.polygon.technology/). This move aligns with our strategy to house the product documentation close by to each other, especially as we introduce the zkValidium, which is based upon Polygon zkEVM.

### Historical Context

Previously, the zkEVM material hosted [here](https://zkevm.polygon.technology/) was under the Polygon Wiki. The team phased it out to cater to stakeholder preferences and to enhance visibility for zkEVM. However, upon reflection, it's evident that segregating this documentation doesn't align with our vision of a cohesive information hub for Polygon.

### Future Context

As we evolve into Polygon 2.0, it's important to note that the core components of the protocol—like runtime environment(s), the bridge, and common core contracts—remain unchanged. These elements are central to the Polygon product documentation. While we'll have varied documentation for different product suites, they all draw from these core components.

## Done Criteria

- [x] Migrate all zkEVM documentation from [zkevm.polygon.technology](https://zkevm.polygon.technology/) to the [Polygon Wiki](https://wiki.polygon.technology/).
- [x] Verify all links, images, and references are operational after migration.
- [x] Ensure server-side redirects are in place.
- [x] Archive the Polygon zkEVM documentation repository.
- [x] Update all references pointing to [zkevm.polygon.technology](https://zkevm.polygon.technology/) on the Polygon Wiki, directing them to the new zkEVM documentation index page.

**Comment by ashucoder9** [comment]
Completed.
